name: build release

permissions:
  contents: write

on:
  push:
    tags: ["*"]
    # To build on main/master branch, uncomment the following line:
    # branches: [ main , master ]

  pull_request:
    branches: [main, master]

  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: vcpkg install wxwidgets:x64-windows-static

      - name: configure
        run: cmake --preset windows-msvc-release

      - name: build
        run: cmake --build --preset release

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          token: ${{ github.token }}
          files: build/windows-msvc-release/sim.exe
          fail_on_unmatched_files: true
          prerelease: ${{ contains(github.ref, '-') }}
