name: Code Quality Check

on:
  push:
    branches:
      - master
    paths:
      - 'src/**'
      - 'CMakeLists.txt'
      - 'CMakePresets.json'
      - 'scripts/**'
  pull_request:
    branches:
      - master
    paths:
      - 'src/**'
      - 'CMakeLists.txt'
      - 'CMakePresets.json'
      - 'scripts/**'

jobs:
  code-quality:
    name: Code Formatting & Linting Check
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Verify clang-tools installation
        run: |
          clang-format --version
          clang-tidy --version
        shell: pwsh

      - name: Check code formatting for compliance
        run: |
          $files = Get-ChildItem -Path src -Recurse -Include *.cpp,*.h
          clang-format --dry-run --Werror --style=file $files
        shell: pwsh # Use PowerShell for Get-ChildItem

      - name: Set up MSVC build environment for the script
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: x64

      - name: Run clang-tidy
        shell: cmd
        run: |
          scripts\lint.bat
